# Publish package on main branch if it's tagged with 'v*'

name: release & publish workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "release"
  release:
    name: Create Release
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/p/eencijfer
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # for publishing to GH-pages
      pages: write # for publishing to GH-pages
    strategy:
      matrix:
        python-versions: ["3.10"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: build documentation
        run: |
          poetry install
          poetry run mkdocs build

      - name: publish documentation
        run: poetry run mkdocs gh-deploy --force

      - name: Build wheels and source tarball
        run: >-
          poetry build

      - name: show temporary files
        run: >-
          ls -l

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
